name: Node.js CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: yarn install, build
      run: |
        yarn install
        yarn build
         
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        node-version: 20
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist

